// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDybm2Fc09K9a2N6Gr5YwLcCRwMhPBhrMo',
    appId: '1:13387436440:web:f52891761ab6998cfb5bed',
    messagingSenderId: '13387436440',
    projectId: 'todo-2b497',
    authDomain: 'todo-2b497.firebaseapp.com',
    storageBucket: 'todo-2b497.firebasestorage.app',
    measurementId: 'G-MXP66PSDXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_k4SoCi6VTLhyQxbl-0ppVKuWmFru_Lo',
    appId: '1:13387436440:android:274588e2f067bde3fb5bed',
    messagingSenderId: '13387436440',
    projectId: 'todo-2b497',
    storageBucket: 'todo-2b497.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6vjjamNS6Hi28NtuIsi9QDOhvS6JjVQg',
    appId: '1:13387436440:ios:e1629dd4fa7b558dfb5bed',
    messagingSenderId: '13387436440',
    projectId: 'todo-2b497',
    storageBucket: 'todo-2b497.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6vjjamNS6Hi28NtuIsi9QDOhvS6JjVQg',
    appId: '1:13387436440:ios:e1629dd4fa7b558dfb5bed',
    messagingSenderId: '13387436440',
    projectId: 'todo-2b497',
    storageBucket: 'todo-2b497.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDybm2Fc09K9a2N6Gr5YwLcCRwMhPBhrMo',
    appId: '1:13387436440:web:b65beb895a92251bfb5bed',
    messagingSenderId: '13387436440',
    projectId: 'todo-2b497',
    authDomain: 'todo-2b497.firebaseapp.com',
    storageBucket: 'todo-2b497.firebasestorage.app',
    measurementId: 'G-RMRDTM9K0K',
  );
}
